### ISSUE TITLE
Lost timestamp packets with VLAN tag

### ISSUE THREAD

**Issue by xzhangxin** [emmericp/MoonGen#152]
Hi,
When I try to measure the latency by using the measureLatency function with VLAN tag, all the sent packets seem to be lost.

	local lat = timestamper:measureLatency(pktSize, function(buf)
		local pkt = buf:getUdpPacket()
		local ethSrc, ethDst, ipSrc, ipDst, vlanID = getNextAddresses()
		pkt:fill {
			pktLength = pktSize,
			udpSrc = PORT_SRC,
			udpDst = PORT_DST,
		}
		pkt.ip4.src:set(ipSrc)
		pkt.ip4.dst:set(ipDst)
		pkt.eth:setSrc(ethSrc)
		pkt.eth:setDst(ethDst)
		buf:setVlan(vlanID,7,0)
	end, maxInterval)

Without buf:setVlan() everything works well and all the packets could be received. Do you have an idea of how could I measure the latency with VLAN tag?

**Comment by emmericp** [comment]
I can confirm that this seems to be broken for UDP timestamps on ixgbe NICs (tested on an X550), L2 timestamps are working.
However, it works with i40e NICs (tested on an X710).

Which NIC are you using?

**Comment by xzhangxin** [comment]
I'm using Intel 82599 Controller, an ixgbe NIC.

Do you mean, it works well with buf:getEthernetPacket() like in the file [l2-load-latency.lua](https://github.com/emmericp/MoonGen/blob/master/examples/l2-load-latency.lua)?

**Comment by emmericp** [comment]
Yes.

I tested this behavior by running  examples/timestamping-tests/test-timestamping-capabilities.lua with an additional line to set the VLAN tag.
I'm currently investigating why this fails on ixgbe but not on i40e.

**Comment by xzhangxin** [comment]
Unfortunately, it doesn't work with following code.

	local lat = timestamper:measureLatency(pktSize, function(buf)
		local pkt = buf:getEthernetPacket()
		local ethSrc, ethDst, ipSrc, ipDst, vlanID = getNextAddresses()
		pkt:fill {
			pktLength = pktSize,
		}
		pkt.eth:setSrc(ethSrc)
		pkt.eth:setDst(ethDst)
		buf:setVlan(vlanID,7,0)
	end, maxInterval)

But it works well without setVlan(), is there something wrong?

**Comment by emmericp** [comment]
you probably didn't change the type of the timestamper to a "normal" timestamper as in l2-load-latency.lua

i added the vlan test case to examples/timestamping-tests/test-timestamping-capabilities.lua

the results are:
i40e (tested XL7100): vlan tags are only supported on UDP packets
ixgbe and igb (tested X550 and 82580): vlan tags are only supported on L2 packets

The reason for the fail is that the NIC doesn't recognize these packets as PTP packets and does not take the timestamp; there is unfortunately nothing we can do about it except for a software timestamping fallback

I'm continuing this in #153 because its a separate issue
