### ISSUE TITLE
RateLimiting on queue throws error "This feature requires a patched driver."

### ISSUE THREAD

**Issue by ashokkumarprajapati** [emmericp/MoonGen#162]
When trying to set rate limit on Tx Queue throws error : 
"Driver does not support disabling the CRC flag. This feature requires a patched driver."

I am running MoonGen on VM with Ubuntu14.04 and Igb_uio driver. Host machine is Ubuntu14.04 and having IXGBE driver  with DPDK 16.04 version.

I am not sure which driver needs to be patched up here. Appreciate help.

**Comment by emmericp** [comment]
How is your VM's network configured?

This feature will only work with PCIe passthrough of a physical function of a supported NIC. It might work with a virtual function, too, but we haven't patched the driver yet/checked whether the NIC supports this.

It's doesn't work by design with virtio & similar virtual nics.
Use a software rate limiter when you have such a setup

**Comment by ashokkumarprajapati** [comment]
Thanks for information.
Just verified that Rate limiting is working on Physical NIC. I was testing with a VM on Openstack, running with VirtIO driver.
I am using now software rate limiter.
