### ISSUE TITLE
Computation of (with framing) throughput in l3-load-latency.lua

### ISSUE THREAD

**Issue by harshgondaliya** [emmericp/MoonGen#285]
From the `libmoon/lua/stats.lua` file, I got to know that 160 bits per packet are being incremented to compute the _with framing_ throughput.

```
	local mbit = (bytes - self.totalBytes) / elapsed / 10^6 * 8
	local wireRate = mbit + (mpps * 20 * 8)

```
Are these 160 bits added to count the 8 bytes Preamble and 12 bytes Inter Frame Gap?

Also, why do we need to separately add these 160 bits? Won't the `bytes - self.totalBytes` be able to give us overall bytes including everything?

**Comment by emmericp** [comment]
Yes, that's exactly where these additional 20 bytes come from :)

We need to add them because the NIC hardware counters do not account for them---at least not on any NIC that I've encountered, most do include CRC (but not all).

So what we have is: Number of packets, total size of all packets but 20 bytes short for each packet.

And what we want is something that adds up to exactly line rate under full load, otherwise it's confusing
