### ISSUE TITLE
802.1Q VLAN support

### ISSUE THREAD

**Issue by TapioT** [emmericp/MoonGen#92]
I started looking at adding VLAN support to MoonGen. Any suggestions?

It seems that the right way is to 

- Add a new header "802.1Q Ethernet header" to headers.lua
- Modify proto/ethernet.lua so that if a VLAN tag is defined, then pkt.getEthernetPacket will use the 802.1Q_Ethernet_header instead of Ethernet_header
- Add to proto/ethernet.lua functions getVLAN and setVLAN
- Make sure that if the fill function has a VLAN tag, then the type is set to 0x8100

Do we need to allow the use case that someone creates an Ethernet packet and then adds a VLAN tag to it? This would probably require copying the packet from old ethernet_header to new 802.1Q_Ethernet_header

**Comment by emmericp** [comment]
I think adding a VLAN tag to the headers is the wrong approach.

It should be a lot easier to use offloading features. I will have a look at that tomorrow.

**Comment by emmericp** [comment]
See commit 3f999fb

You can use it like this:

`buf:setVlan(123)`

or on a bufArray

`bufs:setVlans(123)`

to set the same vlan on all bufs in an bufArray

**Comment by TapioT** [comment]
Thanks, very helpful! I was able to verify that this works.

It seems best to call setVlans after allocating the buffer array.

BTW, I had difficulties in seeing the capital "V" in "setVlans".

**Comment by tristan-corp** [comment]
Hi,
for information, I have tested the feature and found that setVlans works, but it seems that setVlan does not work.

**Comment by emmericp** [comment]
It worked in my tests.
How are you trying to use it?

**Comment by qwe131829** [comment]
l  also have this problem.I added setVlan to pktgen, but I couldn't receive the package after adding it.what's more,l can't captor vlan packets using tcpdump.

**Comment by emmericp** [comment]
if it doesn't work in tcpdump on the receiving side, then it's probably due to filtering or offloading in the network, the driver or somewhere else.

**Comment by qwe131829** [comment]
I have considered this issue, but I  did not receive the packet through the dump-pkt.lua. what is the reason?
  

 

 ------------------ 原始邮件 ------------------
  发件人: "Paul Emmerich"<notifications@github.com>;
 发送时间: 2019年8月12日(星期一) 晚上10:10
 收件人: "emmericp/MoonGen"<MoonGen@noreply.github.com>;
 抄送: "LOVE SICK"<jue99@qq.com>;"Comment"<comment@noreply.github.com>;
 主题: Re: [emmericp/MoonGen] 802.1Q VLAN support (#92)

 

 
if it doesn't work in tcpdump on the receiving side, then it's probably due to filtering or offloading in the network, the driver or somewhere else.

**Comment by qwe131829** [comment]
Hi emmericp！
 I considered this reason, so I tried to use buf:dump() to see whether  vlan header was added after setting VLAN.
  Unfortunately, the information shows that vlan has not been added.
The attachment to the mail is a screenshot of dump()
  
 ------------------ 原始邮件 ------------------
  发件人: "Paul Emmerich"<notifications@github.com>;
 发送时间: 2019年8月12日(星期一) 晚上10:10
 收件人: "emmericp/MoonGen"<MoonGen@noreply.github.com>;
 抄送: "LOVE SICK"<jue99@qq.com>;"Comment"<comment@noreply.github.com>;
 主题: Re: [emmericp/MoonGen] 802.1Q VLAN support (#92)

 

 
if it doesn't work in tcpdump on the receiving side, then it's probably due to filtering or offloading in the network, the driver or somewhere else.

**Comment by emmericp** [comment]
tx: it's offloaded, therefore not visible in the buffer.

rx: it's offloaded by default, therefore stripped in the buffer, use getVlan() to retrieve the stripped tag

**Comment by qwe131829** [comment]
`function txSlave(queue, dstMac)
                buf:getUdpPacket():fill{
                        ethSrc = queue,
                        ethDst = dstMac,
                        ip4Src = SRC_IP,
                        ip4Dst = DST_IP,
                        udpSrc = SRC_PORT,
                        udpDst = DST_PORT,
                        pktLength = PKT_LEN
                }
               buf:setVlan(1234,7,1)
        end)
         local bufs = mempool:bufArray()
        while lm.running() do 
     
                bufs:alloc(PKT_LEN)
       
                for i, buf in ipairs(bufs) do
                      
                                   buf:setVlan(1234,7,1)
                   --     print(buf[i]:getVlan())
                    --       pkt.eth:setType(0x8100)     
                end
                 bufs:offloadUdpChecksums()
                -- print(buf[1]:getVlan())
                      queue:send(bufs)
        end
end
`
I added getVlan to dump-pkts, but it is shown as 0.  Under this code, rx also cannot receive the packet.This makes me very confused.
